"""
RAGAS Example Usage
Demonstrates how to evaluate your RAG system using RAGAS
This script shows two approaches:
1. Evaluate pre-collected Q&A pairs (offline evaluation)
2. Evaluate live RAG pipeline results (online evaluation)

- Measure system quality objectively
- Track improvements over time
- Identify specific weaknesses (retrieval vs generation)
- Compare different configurations (models, chunking, etc.)
"""

from ragas_evaluator import RAGASEvaluator, print_evaluation_report
from ingestion import ingestion_pipeline
from gateway import gateway
from query_processor import query_processor
from retrieval import retrieval_system
from reranker import reranker
from llm_router import llm_router
from validator import validator


def example_1_offline_evaluation():
    """
    Example 1: Evaluate pre-collected Q&A pairs
    USE CASE: You have a test set of questions, answers, and ground truths
    This is the most common approach for systematic evaluation
    """
    print("\n" + "="*60)
    print("EXAMPLE 1: Offline Evaluation with Pre-collected Data")
    print("="*60)
    
    evaluator = RAGASEvaluator()
    
    # Sample test data - in production, load from a file or database
    questions = [
        "What is the refund policy?",
        "How do I contact customer support?",
        "What payment methods do you accept?",
    ]
    
    # Answers generated by your RAG system
    answers = [
        "Our refund policy allows returns within 30 days of purchase with the original receipt.",
        "You can contact customer support via email at support@example.com or call 1-800-SUPPORT.",
        "We accept credit cards, PayPal, and bank transfers for payment.",
    ]
    
    # Contexts retrieved by your RAG system
    contexts = [
        [
            "Our refund policy allows returns within 30 days of purchase with original receipt.",
            "Items must be in original condition and packaging.",
            "Refunds are processed within 5-7 business days."
        ],
        [
            "Contact our support team at support@example.com",
            "Call our hotline at 1-800-SUPPORT (24/7)",
            "Live chat available on our website"
        ],
        [
            "We accept all major credit cards (Visa, MasterCard, American Express)",
            "PayPal payments are supported",
            "Bank transfers available for orders over $100"
        ]
    ]
    
    # Ground truth answers (ideal answers, for context_recall metric)
    ground_truths = [
        "Returns are accepted within 30 days with original receipt in original condition.",
        "Support available at support@example.com, 1-800-SUPPORT, or live chat.",
        "Payment methods: credit cards, PayPal, and bank transfers (over $100).",
    ]
    
    # Run evaluation
    result = evaluator.evaluate(
        questions=questions,
        answers=answers,
        contexts=contexts,
        ground_truths=ground_truths
    )
    
    # Print report
    print_evaluation_report(result)


def example_2_live_pipeline_evaluation():
    """
    Example 2: Evaluate live RAG pipeline results
    USE CASE: Run queries through your RAG system and evaluate the results
    This tests the actual end-to-end performance
    """
    print("\n" + "="*60)
    print("EXAMPLE 2: Live Pipeline Evaluation")
    print("="*60)
    
    # First, ingest some test documents
    print("\nStep 1: Ingesting test documents...")
    test_docs = [
        ("Our company offers a 30-day return policy for all products. Returns must be made with the original receipt and items in original condition.", "return_policy"),
        ("Customer support is available 24/7 via email at support@example.com or phone at 1-800-SUPPORT. Live chat is also available on our website.", "support_info"),
        ("We accept Visa, MasterCard, American Express, PayPal, and bank transfers for orders over $100.", "payment_methods"),
    ]
    
    for text, source in test_docs:
        ingestion_pipeline.ingest_text(
            text=text,
            source=source,
            metadata={"category": "policy"}
        )
    
    print("✓ Documents ingested")
    
    # Test queries
    test_queries = [
        "What is the return policy?",
        "How can I contact support?",
        "What payment methods are accepted?",
    ]
    
    # Run queries through the RAG pipeline
    print("\nStep 2: Running queries through RAG pipeline...")
    rag_results = []
    
    for query in test_queries:
        print(f"  Processing: {query}")
        
        # Gateway
        gateway_result = gateway.process_request(query, user_id="test_user")
        if not gateway_result.is_allowed:
            print(f"    ✗ Blocked by gateway")
            continue
        
        # Query processing
        processed = query_processor.process(gateway_result.scrubbed_query)
        if not processed['should_retrieve']:
            print(f"    ✗ Query out of scope")
            continue
        
        # Retrieval
        documents = retrieval_system.retrieve(
            query_embedding=processed['embedding'],
            query_text=processed['final_query'],
            top_k=20,
            user_id="test_user"
        )
        
        # Re-ranking
        top_docs = reranker.rerank(
            query=query,
            documents=documents,
            top_n=3
        )
        
        # LLM generation
        llm_result = llm_router.route(
            query=query,
            context_docs=top_docs,
            stream=False
        )
        
        # Validation
        validation = validator.validate(
            response=llm_result['response'],
            context_docs=top_docs,
            query=query
        )
        
        # Store result for evaluation
        rag_results.append({
            "question": query,
            "answer": llm_result['response'],
            "contexts": [doc.content for doc in top_docs],
            "ground_truth": None  # No ground truth in live evaluation
        })
        
        print(f"    ✓ Answer generated")
    
    # Evaluate results
    print("\nStep 3: Evaluating results with RAGAS...")
    evaluator = RAGASEvaluator()
    result = evaluator.evaluate_from_rag_pipeline(rag_results)
    
    # Print report
    print_evaluation_report(result)


def example_3_single_query_evaluation():
    """
    Example 3: Evaluate a single query
    USE CASE: Quick check during development or debugging
    """
    print("\n" + "="*60)
    print("EXAMPLE 3: Single Query Evaluation")
    print("="*60)
    
    evaluator = RAGASEvaluator()
    
    question = "What is the refund policy?"
    answer = "Our refund policy allows returns within 30 days of purchase."
    contexts = [
        "Our refund policy allows returns within 30 days of purchase with original receipt.",
        "Items must be in original condition and packaging.",
    ]
    
    result = evaluator.evaluate_single(
        question=question,
        answer=answer,
        contexts=contexts
    )
    
    print("\nSingle Query Evaluation Results:")
    for metric, score in result.items():
        if metric != "overall_score":
            print(f"  {metric}: {score:.4f}")
    print(f"  overall_score: {result['overall_score']:.4f}")


def example_4_ab_testing():
    """
    Example 4: Compare two different RAG configurations
    USE CASE: A/B testing to find the best configuration
    """
    print("\n" + "="*60)
    print("EXAMPLE 4: A/B Testing - Compare Configurations")
    print("="*60)
    
    evaluator = RAGASEvaluator()
    
    # Same test data
    questions = ["What is the refund policy?"]
    
    # Configuration A: Current setup
    answers_a = ["Our refund policy allows returns within 30 days of purchase."]
    contexts_a = [["Our refund policy allows returns within 30 days of purchase with original receipt."]]
    
    # Configuration B: Improved setup (e.g., with re-ranking)
    answers_b = ["Our refund policy allows returns within 30 days of purchase with original receipt. Items must be in original condition."]
    contexts_b = [
        [
            "Our refund policy allows returns within 30 days of purchase with original receipt.",
            "Items must be in original condition and packaging.",
            "Refunds are processed within 5-7 business days."
        ]
    ]
    
    # Evaluate both
    print("\nConfiguration A (Baseline):")
    result_a = evaluator.evaluate(questions, answers_a, contexts_a)
    print(f"  Overall Score: {result_a.overall_score:.4f}")
    
    print("\nConfiguration B (Improved):")
    result_b = evaluator.evaluate(questions, answers_b, contexts_b)
    print(f"  Overall Score: {result_b.overall_score:.4f}")
    
    # Compare
    improvement = result_b.overall_score - result_a.overall_score
    print(f"\nImprovement: {improvement:+.4f}")
    
    if improvement > 0:
        print("✓ Configuration B performs better")
    else:
        print("✗ Configuration A performs better")


def example_5_custom_metrics():
    """
    Example 5: Evaluate with specific metrics only
    USE CASE: Focus on specific aspects (e.g., only retrieval quality)
    """
    print("\n" + "="*60)
    print("EXAMPLE 5: Custom Metrics Selection")
    print("="*60)
    
    evaluator = RAGASEvaluator()
    
    questions = ["What is the refund policy?"]
    answers = ["Our refund policy allows returns within 30 days of purchase."]
    contexts = [["Our refund policy allows returns within 30 days of purchase with original receipt."]]
    
    # Evaluate only retrieval metrics (context precision)
    print("\nEvaluating only retrieval quality (context_precision):")
    result = evaluator.evaluate(
        questions=questions,
        answers=answers,
        contexts=contexts,
        metrics=["context_precision"]
    )
    print(f"  Context Precision: {result.context_precision:.4f}")
    
    # Evaluate only generation metrics (faithfulness, answer_relevancy)
    print("\nEvaluating only generation quality (faithfulness, answer_relevancy):")
    result = evaluator.evaluate(
        questions=questions,
        answers=answers,
        contexts=contexts,
        metrics=["faithfulness", "answer_relevancy"]
    )
    print(f"  Faithfulness: {result.faithfulness:.4f}")
    print(f"  Answer Relevancy: {result.answer_relevancy:.4f}")


if __name__ == "__main__":
    print("\n" + "="*60)
    print("RAGAS EVALUATION EXAMPLES")
    print("="*60)
    print("\nThis script demonstrates different ways to use RAGAS")
    print("to evaluate your RAG system.")
    print("\nNote: RAGAS is configured to use AWS Bedrock for evaluation")
    print("using your existing AWS credentials from .env file.\n")
    
    # Run examples
    try:
        example_1_offline_evaluation()
        print("\n" + "="*60)
        
        # Uncomment to run live pipeline evaluation (requires Qdrant running)
        # example_2_live_pipeline_evaluation()
        # print("\n" + "="*60)
        
        example_3_single_query_evaluation()
        print("\n" + "="*60)
        
        example_4_ab_testing()
        print("\n" + "="*60)
        
        example_5_custom_metrics()
        print("\n" + "="*60)
        
    except Exception as e:
        print(f"\nError running examples: {e}")
        print("\nTroubleshooting:")
        print("1. Ensure AWS credentials are set in .env file")
        print("2. Ensure Bedrock is enabled in your AWS region")
        print("3. Ensure you have access to Claude models in Bedrock")
        print("4. Check that your IAM user has bedrock:InvokeModel permissions")
        print("\nSome examples require Qdrant and AWS Bedrock to be configured.")
        print("Example 1, 3, 4, and 5 work with sample data.")
    
    print("\n✓ Examples completed")
    print("\nNext steps:")
    print("1. Create your own test dataset with questions and ground truths")
    print("2. Run evaluation on your RAG system outputs")
    print("3. Track scores over time to measure improvements")
    print("4. Use A/B testing to compare different configurations")
